table 'month sales trend'
	lineageTag: fdfabffb-a1a2-46ce-9487-29ebd90cddb2

	column month
		dataType: dateTime
		formatString: Long Date
		lineageTag: a8e828f2-a2c9-41dc-8dbc-01a05df99de2
		summarizeBy: none
		sourceColumn: month

		variation Variation
			isDefault
			relationship: 59c6b62d-b252-44a8-8c78-caa11e52ee48
			defaultHierarchy: LocalDateTable_9355061f-4bb0-443e-aaf3-7321a146bafa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column total_transactions
		dataType: int64
		formatString: 0
		lineageTag: 4b60f5bc-0f67-4402-847b-61ea3b9c19c2
		summarizeBy: sum
		sourceColumn: total_transactions

		annotation SummarizationSetBy = Automatic

	column total_sales
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: 983b6018-6eaf-4367-88e7-ee787dc59313
		summarizeBy: sum
		sourceColumn: total_sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	partition 'month sales trend' = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\anant\OneDrive\Desktop\Coffee Shop Sales\sql tables\month sales trend.csv"), [Delimiter = ",", Columns = 3, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"month", type date}, {"total_transactions", Int64.Type}, {"total_sales", type number}}, "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed column type",{{"total_sales", Currency.Type}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

