table 'store sales trend'
	lineageTag: 387f773c-6724-422d-a12f-ca6ffd63b48b

	column store_location
		dataType: string
		lineageTag: 86603f1e-e5d1-454c-8493-029a9c92f178
		summarizeBy: none
		sourceColumn: store_location

		annotation SummarizationSetBy = Automatic

	column total_revenue
		dataType: decimal
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		lineageTag: cee31c0e-065a-40c2-903e-cc84d6b2ed70
		summarizeBy: none
		sourceColumn: total_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	partition 'store sales trend' = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\anant\OneDrive\Desktop\Coffee Shop Sales\sql tables\store sales trend.csv"), [Delimiter = ",", Columns = 2, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"store_location", type text}, {"total_revenue", type number}}, "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed column type",{{"total_revenue", Currency.Type}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

